
\section{MCMC in the SSP model}

In the SSP, our sample collection includes $N$ samples with $L$ SNP loci.  Only the genotypes of the sampled individuals, $y_{i,\ell}, are 
known. The contamination rate, $\rho$, the allele frequency of the "1" allele at the $\ell^{th}$ locus, $\theta_{\ell}$, and the indicator variable $z_i$ are unknown paramenters.  

Values for $\rho$, $\theta_{\ell}$, and $z_i$ were updated using Gibbs sampling, which required the derivation of the full conditional distributions of the paramenters. The formula for the full conditional of $z_i$ is given Eq. \ref{z_fc}.

\begin{equation} \label{z_fc}
P(z_i|\theta_{\ell},y_i) = P(z_i|\rho)P(y_i|z_i,\theta)
\end{equation}
$P(z_i|\rho)$ is the likelihood of the $z_i$ value given $\rho$, and $P(y_i|z_i,\theta)$ is the likelihood of the genotype given $z_i$ and $\theta$.  A Bernoulli distribution gives the likelihood of $z_i$:

\begin{equation} \label{z_lh}
P(z_i|\rho) = \rho^{z_i}(1-\rho)^{1-z_i} 
\end{equation}


\begin{equation} \label{y_lh}
P(y_i|z_i=0,\theta) = \prod_{\ell=1}^{L} P(y_{\ell}|\theta_{\ell},noncontam)
\end{equation}
\begin{equation} \label{y_lhc}
P(y_i|z_i=1,\theta) = \prod_{\ell=1}^{L} P(y_{\ell}|\theta_{\ell},contam)
\end{equation}
The full conditional distribution of $z_i$ used in the MCMC model,given by Eq. \ref{z_simpfc}, is derived by substituting Eq. \ref{z_lh}, Eq. \ref{y_lh}, and Eq. \ref{y_lhc} into Eq. \ref{z_fc}.
\begin{eqnarray} \label{z_simpfc}
P(z_i=0|\theta_{\ell},y_i) &=& \frac{(1-\rho)^{1-z_i}\prod_{\ell=1}^{L} P(y_{\ell}|\theta_{\ell},noncontam)}{R} \nonumber \\
P(z_i=1|\theta_{\ell},y_i) &=& \frac{\rho^{z_i}\prod_{\ell=1}^{L} P(y_{\ell}|\theta_{\ell},contam)}{R} \nonumber \\
R &=& (1-\rho)^{1-z_i}\prod_{\ell=1}^{L} P(y_{\ell}|\theta_{\ell},noncontam) \nonumber \\
& & +\rho^{z_i}\prod_{\ell=1}^{L} P(y_{\ell}|\theta_{\ell},contam) 
\end{eqnarray}
Dividing by R normalizes the distribution. \\


The formula for the full conditional distribution for $\rho$ is given by:
  \begin{equation} \label{rho_fc}
    P(\rho|z_i) \propto [\prod_{i=1}^{N} P(z_i|\rho)] P(\rho|\alpha,\beta)
  \end{equation}
As shown below, substituting Eq. \ref{z_lh} and Eq. \ref{rho_prior} into Eq. \ref{rho_fc} can reduce the full conditional distribution of $\rho$ to a beta distribution with parameters $(\alpha + \sum_{i=1}^{N} z_i)$ and $(\beta + N - \sum_{i=1}^{N} z_i)$ as shown below:

\begin{eqnarray} \label{rho_simpfc}
  P(\rho|z_i) &\propto& [\prod_{i=1}^{N} P(z_i|\rho)] p    (\rho|\alpha,\beta) \nonumber \\
  &=& [\prod_{i=1}^{N} \rho^{z_i}(1 - \rho)^{1 - z_i}] \rho^{\alpha - 1}(1 - \rho)^{\beta-1} \nonumber \\
  &=& \rho^{\sum_{i=1}^{N} z_i}(1-\rho)^{N - \sum_{i=1}^{N} z_i} \rho^{\alpha -1} (1-\rho)^{\beta-1} \nonumber \\
  &=& \rho^{\alpha - 1 + \sum_{i=1}^{N} z_i}(1 - \rho)^{\beta -1 + N - \sum_{i=1}^{N} z_i}
\end{eqnarray}

The formula for full conditional distribution of $\theta_{\ell}$ given by:

\begin{equation} \label{theta_fc}
P(\theta_{\ell}|y_{i\ell},z_i) \propto [\prod_{i=\ell}^{N} P(y_{i\ell}|\theta_{\ell},z_i)]P(\theta_{\ell}|\lambda_{\ell})
\end{equation}

Only non-contaminated genotypes are used to calculate allele frequencies.  Therefore, only non-contaminated samples are relevant for the full condition distribution of $\theta_{\ell}$.  The likelihood of $y_{i\ell}$ given $\theta_{\ell}$ and non-contamination, $P(y_{i\ell}|\theta_{\ell},noncontam)$, is calculated assuming that the population is in Hardy-Weinberge Equilibrium. Evaluating $P(y_{i\ell}|\theta_{\ell},noncontam)$ and substituting Eq \ref{theta_prior} into Eq \ref{theta_fc} symplifies the full conditional distribution of $\theta_{\ell}$ to a beta distribution with parameters $(2x_2 + x_1 + \lambda_{\ell})$ and $(2x_0 + x_1 + \lambda_{\ell})$ where $x_j = \sum_{i:z=0}^{N} \delta(y_{i\ell} = j)$. 

\begin{eqnarray} \label{theta_simpfc}
P(\theta_{\ell}|y_{i\ell},z_i) &\propto& [\prod_{i=\ell}^{N} P(y_{i\ell}|\theta_{\ell},z_i)]P(\theta_{\ell}|\lambda_{\ell}) \nonumber \\
&=& [\prod_{i:z=0}^{N} P(y_{i\ell}|\theta_{\ell},noncontam)] \nonumber \\
& & \times \theta_{\ell}^{\lambda_{\ell} - 1}(1-\theta_{\ell})^{\lambda_{\ell} - 1} \nonumber \\
&=& [(1-\theta_{\ell})^2]^{x_0}[2\theta_{\ell}(1-\theta_{\ell})]^{x_1}[\theta_{\ell}^2]^{x_2} \nonumber \\
& & \times \theta_{\ell}^{\lambda_{\ell} - 1}(1 - \theta_{\ell})^{\lambda_{\ell} - 1} \nonumber \\
& \propto& \theta_{\ell}^{2x_0 + x_1 + \lambda_{\ell} - 1}(1-\theta_{\ell})^{2x_0 + x_1 + \lambda_{\ell} - 1}
\end{eqnarray}

\section{MCMC in the MSP model}

In the MSP, our sample collection includes $N$ samples with $L$ SNP loci from $P$ populations.  The genotypes of the sampled individuals, $y_{i,\ell}, and the baseline data, $B$, are the only known parameters. The contamination rate, $\rho$, the mixing proprotions, $\pi$, the indicator variable $u_i$, and the indicator variable $z_i$ are unknown paramenters.  

Values for $\rho$, $\pi$, $u_i$, and $z_i$ were updated using Gibbs sampling.  The full conditional distribution of $\rho$ is the distribution used in the SSP model  The formula for the full conditional of $z_i$ is given Eq. \ref{z_fc}.