// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// P_likelihood
NumericMatrix P_likelihood(NumericMatrix gc, IntegerMatrix genos, double lambda);
RcppExport SEXP SNPcontam_P_likelihood(SEXP gcSEXP, SEXP genosSEXP, SEXP lambdaSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< NumericMatrix >::type gc(gcSEXP );
        Rcpp::traits::input_parameter< IntegerMatrix >::type genos(genosSEXP );
        Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP );
        NumericMatrix __result = P_likelihood(gc, genos, lambda);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
